#! /usr/bin/env sh

while getopts "hpf:d:" opt; do
  case $opt in
    p)
      OUTPUT_PAGE="html"
      ;;
    f)
      echo "-f using file: $OPTARG" >&2
      MV_FILE=$OPTARG
      ;;
    d)
      echo "-d using output: $OPTARG" >&2
      OUT_DIR=$OPTARG
      ;;
    g)
      echo "-g using external metadata file: $OPTARG" >&2
      MET_FILE=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      exit 1
      ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1
      ;;
  esac
done

if [ -z "$MV_FILE" ]; then
    if [ -f "$1" ]; then
        MV_FILE="$1"
    else
        echo "Movie file not set" >&2
        exit 1
    fi
fi

if [ ! -f "$MV_FILE" ]; then
    echo "Movie file not found" >&2
    exit 1
fi

cd $PWD

if [ -f "$MV_FILE.md" ]; then
        rm "$MV_FILE.md"
fi

export bn=$(basename "$MV_FILE")
export dn=$(dirname "$MV_FILE" | sed 's|./||')

pretext=$(metaname "$MV_FILE")

titles=$(echo "$pretext" | grep 'Title:' | sed 's|Title: |# |')
echo "$titles" | tee "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md" | tee -a "$OUT_DIR/$bn.md"
echo "<video width=\"92%\" src=\""'../'"$dn"'/'"$bn\" type=\"video/mp4\">" | tee -a "$OUT_DIR/$bn.md"
echo "video" | tee -a "$OUT_DIR/$bn.md"
echo "</video>" | tee -a "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md"
echo $(echo "$pretext" | grep 'Season:' | sed 's|Season: |## Season: |') $(echo "$pretext" | grep 'Episode:' | sed 's|Episode:| Episode:|') | tee -a "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md"
echo "$pretext" | grep 'Description:' | sed 's|Description: |##### Description: |' | tee -a "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md"
echo "$pretext" | grep 'Date:' | sed 's|Date: |#### Date: |' | tee -a "$OUT_DIR/$bn.md"
echo "$pretext" | grep 'Year:' | sed 's|Year: |#### Year: |' | tee -a "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md"
echo "$pretext" | grep 'Director:' | sed 's|Director: |##### Director: |' | tee -a "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md"
echo "$pretext" | grep 'License:' | sed 's|License: |##### License: |' | tee -a "$OUT_DIR/$bn.md"
echo | tee -a "$OUT_DIR/$bn.md"

title=$(echo "$titles" | tr -d '# \n')

if [ ! -z "$OUTPUT_PAGE" ]; then
        hdpage -p -t "$title" | tee "$OUT_DIR/$bn.html"
        echo "  <body>" | tee -a "$OUT_DIR/$bn.html"
        markdown "$OUT_DIR/$bn.md" | tee -a "$OUT_DIR/$bn.html"
        echo "  </body>" | tee -a "$OUT_DIR/$bn.html"
        echo "</html>" | tee -a "$OUT_DIR/$bn.html"

fi
